SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT;
SET NAMES utf8;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO';


DROP PROCEDURE IF EXISTS rkr__stack__push;
DELIMITER //
CREATE PROCEDURE rkr__stack__push(INOUT stack LONGTEXT CHARSET utf8, IN val LONGTEXT CHARSET utf8)
    NO SQL
    SQL SECURITY INVOKER
	DETERMINISTIC
BEGIN
	IF ISNULL(val) THEN
		SET stack = CONCAT('N:::', stack);
	ELSE
		SET stack = CONCAT('S:', LENGTH(val), ':', val, ':', stack);
	END IF;
END//
DELIMITER ;


DROP PROCEDURE IF EXISTS rkr__stack__pop;
DELIMITER //
CREATE PROCEDURE rkr__stack__pop(INOUT stack LONGTEXT CHARSET utf8, OUT val LONGTEXT CHARSET utf8)
	NO SQL
	SQL SECURITY INVOKER
	DETERMINISTIC
BEGIN
	DECLARE type CHAR CHARSET utf8;
	DECLARE pos INT;
	DECLARE len INT;

	SET type = SUBSTR(stack, 1, 1);

	IF type = 'N' THEN
		SET val = null;
		SET stack = SUBSTRING(stack, 5);
	ELSE
		SET pos = LOCATE(':', stack, 3);
		SET len = SUBSTRING(stack, 3, pos - 3);
		SET val = SUBSTRING(stack, pos + 1, len);
		SET stack = SUBSTRING(stack, pos + len + 2);
	END IF;
END//
DELIMITER ;


SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '');
SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS);
SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT;
