SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT;
SET NAMES utf8;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO';


DROP FUNCTION IF EXISTS rkr__xml__escape;
DELIMITER //
CREATE FUNCTION rkr__xml__escape(arg_data LONGTEXT CHARSET utf8)
	RETURNS LONGTEXT CHARSET utf8
    NO SQL
    SQL SECURITY INVOKER
    DETERMINISTIC
BEGIN
	SET arg_data = REPLACE(arg_data, '&', '&amp;');
	SET arg_data = REPLACE(arg_data, '<', '&lt;');
	SET arg_data = REPLACE(arg_data, '>', '&gt;');
	SET arg_data = REPLACE(arg_data, '"', '&quot;');
	RETURN arg_data;
END//
DELIMITER ;


SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '');
SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS);
SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT;
