DELIMITER //


DROP PROCEDURE IF EXISTS rkr$debug//
CREATE PROCEDURE rkr$debug(IN text LONGTEXT CHARSET utf8)
	NO SQL
	SQL SECURITY INVOKER
	DETERMINISTIC
BEGIN
	SET @debug = CONCAT(@debug, "\n", text);
END//


DELIMITER ;
